server:server:
  port: 8080

jwt:
  secret: ${JWT_SECRET:2LM1OEf2filBHvqs2JMdaQBj2sWCqg7g}

spring:
  cloud:
    gateway:
      default-filters:
        - PreserveHostHeader
      routes:
        # Auth service (login/registro)
        - id: auth-service
          uri: http://localhost:8081
          predicates:
            - Path=/auth/**

        # Task service: tareas
        - id: task-service-tareas
          uri: http://localhost:8082
          predicates:
            - Path=/api/v1/tareas/**
          filters:
            - name: AuthenticationFilter

        # Task service: pacientes (cotizantes y beneficiarios)
        - id: task-service-pacientes
          uri: http://localhost:8082
          predicates:
            - Path=/api/v1/pacientes/**
          filters:
            - name: AuthenticationFilter

  webflux:
    cors:
      filter:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:5500"
              - "http://127.0.0.1:5500"
            allowedMethods:
              - GET
              - POST
              - PUT
              - PATCH
              - DELETE
            allowedHeaders:
              - "*"
            allowCredentials: true
            maxAge: 3600
