server:
  port: 8080

jwt:
  secret: ${JWT_SECRET:2LM1OEf2filBHvqs2JMdaQBj2sWCqg7g}

spring:
  cloud:
    gateway:
      default-filters:
        - PreserveHostHeader
      routes:
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/auth/**

     # Ruta para el servicio de tareas (protegida)
        - id: task_service_route # Un ID único para esta ruta
          # CORREGIDO: Usando el service ID en lugar de una URL fija
          uri: lb://tasks-service
          predicates:
            - Path=/api/v1/tareas/**
          # ¡AÑADIDO! Aplicando el filtro de seguridad a esta ruta
          filters:
            - name: AuthenticationFilter # Todas las peticiones que empiecen con /api/v1/tareas/

  webflux:
    cors:
      filter:
        corsConfigurations:
          '[/**]': # Aplica la configuración a todas las rutas (/**)
            allowedOrigins:
              - "http://localhost:5500" # Permite solicitudes desde tu frontend (ej. Live Server de VS Code)
              - "http://127.0.0.1:5500" # A veces, el navegador usa 127.0.0.1 en lugar de localhost
            allowedMethods:
              - GET
              - POST
              - PUT
              - PATCH
              - DELETE
            allowedHeaders:
              - "*" # Permite todos los headers
            allowCredentials: true # Permite el envío de credenciales (cookies, headers de autorización)
            maxAge: 3600 # Cachea los resultados de la pre-verificación de CORS por 1 hora